#!/bin/bash

file="${1:-crypt.enc}"
[ -z "$2" ] && read -rsp "Enter secret: " secret && echo "" || secret=$(cat "$2")
echo -n "$secret" | openssl enc -aes-256-cbc -salt -pbkdf2 -iter 100000 -e -out "$file"
